# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    sources:
    - sourceline: 'ppa:cran/imagemagick'
    packages:
    - libmagick++-dev
    - libglu1-mesa-dev

before_script:
  - Rscript -e 'remotes::install_github("rmaia/pavo", dependencies = TRUE)'
